<?php
/**
 *
 * @date
 * @author Oleksii Bogatchenko
 * @package composer-preloader-plugin
 * @version 1.0
 */

namespace Oleksii\ComposerPreloader\Composer\PreloadGenerator;

use  MJS\TopSort\Implementations\StringSort;

class PreloadGenerator {

    private Config $config;

    public function __construct(Config $config)
    {
        $this->config = $config;
    }

    public function generate()
    {
        $finder = new Finder($this->config);
        $fileList = $finder->findFiles();
        $enumFiles = [];


        $sorter = new StringSort();
        $sorter->setThrowCircularDependency(false);


        foreach ($fileList as $fileInfo) {
            if($this->config->isUseIncludeForEnumFiles() && $fileInfo['isEnum']) {
                $enumFiles[] = $fileInfo['path'];
            }

            $sorter->add($fileInfo['path'], $fileInfo['deps']);

        }

        $sorted = $sorter->sort();
        $rootDir = realpath(dirname(\Composer\Factory::getComposerFile()));
        $outputFile = fopen( $rootDir . DIRECTORY_SEPARATOR . $this->config->getOutputFile(), 'w');
        fwrite($outputFile, $this->renderHeader());

        $writedFiles = [];

        foreach ($enumFiles as $enumFile) {
            fwrite($outputFile, $this->renderIncludeFile($enumFile));
            $writedFiles[] = $rootDir . DIRECTORY_SEPARATOR . $enumFile;
        }

        foreach ($sorted as $filePath) {
            if(!in_array($filePath, $enumFiles)) {
                fwrite($outputFile, $this->renderFile($filePath));
                $writedFiles[] = $rootDir . DIRECTORY_SEPARATOR . $filePath;
            }

        }

        fclose($outputFile);

        file_put_contents($rootDir . DIRECTORY_SEPARATOR . $this->config->getListOutputFile(), '<?php' . PHP_EOL  .
            'return ' . var_export($writedFiles, true). ';' );
    }

    private function renderHeader()
    {
        $code = <<<PHP
<?php
/** Generated by composer-preloader-plugin */
\$rootDir = \dirname(__DIR__);

if (!\\function_exists('opcache_compile_file') || !\\ini_get('opcache.enable')) {
  echo 'Opcache is not available.';
  die(1);
}

if ('cli' === \\PHP_SAPI && !\\ini_get('opcache.enable_cli')) {
  echo 'Opcache is not enabled for CLI applications.';
  die(2);
}

PHP;

        return $code;

    }

    private function renderIncludeFile(string $filePath) : string
    {
        $code = <<<PHP
include \$rootDir . \\DIRECTORY_SEPARATOR  .  '$filePath';

PHP;

        return $code;

    }
    private function renderFile(string $filePath) : string
    {
        $code = <<<PHP
\\opcache_compile_file(\$rootDir . \\DIRECTORY_SEPARATOR  .  '$filePath');

PHP;

        return $code;
    }
}