<?php
use Oleksii\ComposerPreloader\Composer\Generator\Config;
use Oleksii\ComposerPreloader\Composer\Generator\Writer\Writer;
use PHPUnit\Framework\TestCase;
use Composer\IO\NullIO;

final class WriterTest extends TestCase
{
    private function ensureDir(string $dir): void
    {
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }
    }

    public function testWritesPreloaderHeaderWithEmptyLists(): void
    {
        $root = getcwd();
        $outDir = $root . DIRECTORY_SEPARATOR . 'tests' . DIRECTORY_SEPARATOR . 'tmp';
        $this->ensureDir($outDir);
        $outFile = 'tests' . DIRECTORY_SEPARATOR . 'tmp' . DIRECTORY_SEPARATOR . 'preload.php';

        $config = new Config();
        $config->setRootDir($root);
        $config->setOutputFile($outFile);
        $config->setListOutputFile(''); // disable list file to avoid buggy path

        $writer = new Writer($config, new NullIO());
        $result = $writer->writePreloaderFile([], []);

        $this->assertFileExists($outDir . DIRECTORY_SEPARATOR . 'preload.php');
        $contents = file_get_contents($outDir . DIRECTORY_SEPARATOR . 'preload.php');
        $this->assertIsString($contents);
        $this->assertStringContainsString('Generated by composer-preloader-plugin', $contents);
        $this->assertSame(0, $result->getWritedFiles());
        $this->assertSame(0, $result->getEnumFiles());
    }
}
